/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pet_license;

import java.awt.Image;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author 63936
 */
public class Registration_Form extends javax.swing.JFrame {
    
    private int id;
    private String firstN;
    private String lastN;
    private String edad;
    private String cont;
    private String barang;
    private String muni;
    private String pro;
    private String accounts;
    private String passwords;
    private int month;
    private int day;
    private int year;
    /**
     * Creates new form registration
     */
    
    public void currentDate(){
        Calendar cal = new GregorianCalendar();
        this.month =cal.get(Calendar.MONTH)+1;
        this.day = cal.get(Calendar.DAY_OF_MONTH);
        this.year = cal.get(Calendar.YEAR);
                
               
    }
    public Registration_Form(int id, String firstN, String lastN, String edad, String cont, String barang, String muni, String pro, String accounts, String passwords) throws IOException {
    initComponents();
    currentDate();
        Image icon = ImageIO.read(getClass().getResource("/images/logo.png"));
        this.setIconImage(icon);
        this.setTitle("FURLICENSE");
        this.id = id;
    this.firstN =firstN;
    this.lastN=lastN;
    this.edad=edad;
    this.cont=cont;
    this.barang=barang;
    this.muni=muni;
    this.pro = pro;
    this.accounts = accounts;
    this.passwords = passwords;
        
        System.out.print(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        petName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        petBreed = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        petGender = new javax.swing.JComboBox<>();
        petType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        petBDate = new javax.swing.JTextField();
        petBYear = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        petWeight = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        petHeight = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        petVacDate = new javax.swing.JTextField();
        petVacYear = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        VacId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pBMonth = new javax.swing.JComboBox<>();
        petVacMonth = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(830, 530));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(199, 186, 158));
        jScrollPane2.setHorizontalScrollBar(null);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(830, 526));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(830, 526));

        jPanel3.setBackground(new java.awt.Color(199, 186, 158));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRATION FORM");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(133, 112, 67));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 54, 36));

        petName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(petName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 376, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PET'S INFORMATION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 250, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Animal Type :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Breed :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        petBreed.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(petBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 380, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        petGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        petGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(petGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 160, -1));

        petType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        petType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dog", "Cat" }));
        jPanel1.add(petType, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 160, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Birthday :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 30));

        petBDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        petBDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(petBDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 70, -1));

        petBYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        petBYear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(petBYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 120, -1));

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Month");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, 40));

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Day");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, 40));

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Year");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 30, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Weight (in kl):");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 30));

        petWeight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(petWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 380, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Height  (in cm):");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 20));

        petHeight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(petHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 380, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date of Vaccination :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, 30));

        petVacDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        petVacDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(petVacDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 100, -1));

        petVacYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        petVacYear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(petVacYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 100, -1));

        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Month");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, 60));

        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Day");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 40, 40));

        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Year");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 30, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Vaccination Serial # :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, 30));

        VacId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(VacId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 380, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, 30));

        pBMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPanel1.add(pBMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 120, 30));

        petVacMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPanel1.add(petVacMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 100, 30));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 841, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    try {
        // Load the MySQL driver
        Class.forName("com.mysql.cj.jdbc.Driver");

        // Establish connection
        String url = "jdbc:mysql://localhost:3306/pet_license";
        Connection con = DriverManager.getConnection(url, "root", "");

        // SQL query to select account based on account name and password
        String query = "SELECT * FROM account_info WHERE account_name = ? AND password = ?";
        PreparedStatement pst = con.prepareStatement(query);

        // Set the values for the prepared statement
        pst.setString(1, this.accounts);  // Set the account name
        pst.setString(2, this.passwords);   // Set the password

        // Execute the query
        ResultSet rs = pst.executeQuery();

        // Check if the result set contains a matching user
        if (rs.next()) {
            int pri = rs.getInt("ID");
            String firstName = rs.getString("First_Name"); // Get First Name
            String lastName = rs.getString("Last_Name");   // Get Last Name
            String age = rs.getString("Birth_Date"); // Get Middle Name
            String address = rs.getString("baranggay");    // Get Address
            String contact = rs.getString("contact_number");
            String city = rs.getString("City");          // Get City (or another field you might want to display)
            String province = rs.getString("province");
            String account = rs.getString("account_name");
            String password = rs.getString("password");
            
            // Pass user details to the Main_Dash_Board constructor
            Main_Dash_Board pi = new Main_Dash_Board(pri,firstName, lastName,age, contact, address, city, province, account, password);
            pi.setVisible(true);
            this.dispose(); // Close the current frame
        } else {
            // If no matching user found, show an error message
            JOptionPane.showMessageDialog(this, "Invalid username or password.");
        }

        // Close the ResultSet and PreparedStatement
        rs.close();
        pst.close();
        con.close();

    } catch (ClassNotFoundException | SQLException e) {
        // Handle the exception (e.g., display an error message)
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }   catch (IOException ex) {
            Logger.getLogger(Registration_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                   
    String petN1 = petName.getText();
    
    String type = (String) petType.getSelectedItem();
    String petbreed2 = petBreed.getText();
    String petbreed = petbreed2.isEmpty() ? "" : petbreed2.substring(0, 1).toUpperCase() + petbreed2.substring(1).toLowerCase();
    String petgen = (String) petGender.getSelectedItem();
    String bMonth = (String) pBMonth.getSelectedItem();
    String bDate = petBDate.getText();
    String bYear = petBYear.getText();
    String pWeight = petWeight.getText();
    String pHeight = petHeight.getText();
    String vacMonth = (String) petVacMonth.getSelectedItem();
    String vacDate = petVacDate.getText();
    String vacYear = petVacYear.getText();
    String vacId = VacId.getText();
    
   
     if (petN1.isEmpty() || type.isEmpty() || petbreed.isEmpty() || petgen.isEmpty() || 
        bMonth.isEmpty() || bDate.isEmpty() || bYear.isEmpty() || pWeight.isEmpty() || pHeight.isEmpty() ||
        vacMonth.isEmpty() || vacDate.isEmpty() || vacYear.isEmpty() || vacId.isEmpty()) {
        
        JOptionPane.showMessageDialog(this, "Please fill out all fields.", "Input Required", JOptionPane.WARNING_MESSAGE);
        return; // Exit the method if validation fails
    }
    String petN = petN1.substring(0, 1).toUpperCase() + petN1.substring(1).toLowerCase();
     
    try {
        // Load the MySQL driver
        Class.forName("com.mysql.cj.jdbc.Driver");

        // Establish connection
        String url = "jdbc:mysql://localhost:3306/pet_license";
        Connection con = DriverManager.getConnection(url, "root", "");

        // Check if the connection is successful
        if (con != null) {
            System.out.println("Connection successful.");
        } else {
            System.out.println("Connection failed.");
        }

        // Prepare the SQL query
        String query = "INSERT INTO pet_info(name, type, breed, gender, birth_month, birth_date, birth_year, pet_weight, pet_height, vaccine_month, vaccine_date, vaccine_year, vaccine_id, account_used,Request_For,Request_sent) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
        PreparedStatement pst = con.prepareStatement(query);

        // Set parameters
        String date = this.month +"/"+ this.day +"/"+ this.year;
        pst.setString(1, petN);
        pst.setString(2, type);
        pst.setString(3, petbreed);
        pst.setString(4, petgen);
        pst.setString(5, bMonth);
        pst.setString(6, bDate);
        pst.setString(7, bYear);
        pst.setString(8, pWeight);
        pst.setString(9, pHeight); // Corrected parameter usage
        pst.setString(10, vacMonth);
        pst.setString(11, vacDate);
        pst.setString(12, vacYear);
        pst.setString(13, vacId);
        pst.setString(14, this.accounts); // Ensure this.accounts is initialized
        pst.setString(15, "REGISTRATION");
        pst.setString(16,date);

        // Execute the insert
        int rowsAffected = pst.executeUpdate();

        // Provide feedback
        if (rowsAffected > 0) {
            System.out.println("Record inserted successfully.");
            JOptionPane.showMessageDialog(this, "Request sent!");
            jButton2ActionPerformed(evt);
            this.dispose();
        } else {
            System.out.println("Failed to insert the record.");
        }

        // Close the connection
        pst.close();
        con.close();

    } catch (ClassNotFoundException e) {
        System.out.println("MySQL JDBC Driver not found!");
        e.printStackTrace();
    } catch (SQLException e) {
        System.out.println("SQLException: " + e.getMessage());
        e.printStackTrace();
    }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int id = 0;
                String firstN = null;
                String lastN = null;
                String edad = null;
                String cont = null;
                String barang = null;
                String muni = null;
                String pro = null;
                String accounts = null;
                String passwords = null;
                try {
                    new Registration_Form(id,firstN, lastN, edad, cont, barang, barang, barang, accounts, passwords).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Registration_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
                
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField VacId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> pBMonth;
    private javax.swing.JTextField petBDate;
    private javax.swing.JTextField petBYear;
    private javax.swing.JTextField petBreed;
    private javax.swing.JComboBox<String> petGender;
    private javax.swing.JTextField petHeight;
    private javax.swing.JTextField petName;
    private javax.swing.JComboBox<String> petType;
    private javax.swing.JTextField petVacDate;
    private javax.swing.JComboBox<String> petVacMonth;
    private javax.swing.JTextField petVacYear;
    private javax.swing.JTextField petWeight;
    // End of variables declaration//GEN-END:variables

    
}
