/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pet_license;

import java.awt.Image;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import java.text.SimpleDateFormat;

/**
 *
 * @author 63936
 */
public class Sign_Up extends javax.swing.JFrame {

    /**
     * Creates new form Sign_Up
     */
    public Sign_Up() throws IOException {
        
        initComponents();
        Image icon = ImageIO.read(getClass().getResource("/images/logo.png"));
        this.setIconImage(icon);
        this.setTitle("FURLICENSE");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        contactNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        baranggay = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        municipality = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        account = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(199, 186, 158));
        jPanel1.setMinimumSize(new java.awt.Dimension(550, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 488));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(133, 112, 67));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN UP to FurLicense");
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 130, -1));
        jPanel2.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 130, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("First Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 50, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Last Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 50, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Birth Day :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact Number :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        jPanel2.add(contactNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 250, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Baranggay :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        jPanel2.add(baranggay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 270, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Municipality :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        jPanel2.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 270, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Province :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
        jPanel2.add(municipality, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 270, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Account Name :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        jPanel2.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 270, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 270, -1));

        jButton1.setBackground(new java.awt.Color(199, 186, 158));
        jButton1.setText("DONE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 100, 40));

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Already had an Account?");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Log In");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, 20));

        jDateChooser1.setDateFormatString("MMMM d, yyyy");
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 270, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("09");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 20, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 510, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    @SuppressWarnings("empty-statement")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
           
    String nam1 = name.getText();
    String last1 = lastName.getText();
    Date agE = jDateChooser1.getDate();
    String con_num = "09" + contactNum.getText();
    String baranggaY1 = baranggay.getText();
    String citY1 = city.getText();
    String municipal1 = municipality.getText();
    String user = account.getText();
    String pass = password.getText();

    
    if (nam1 == null || nam1.trim().isEmpty() || last1 == null || last1.trim().isEmpty() || agE == null || con_num == null || con_num.trim().isEmpty() || baranggaY1 == null || baranggaY1.trim().isEmpty() || citY1 == null || citY1.trim().isEmpty() || municipal1 == null || municipal1.trim().isEmpty() || user == null || user.trim().isEmpty() || pass == null || pass.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Make sure there is no blank input", "Input Required", JOptionPane.WARNING_MESSAGE);
        return;  // Avoid executing the insert if the name is empty
    }
       if (con_num.trim().isEmpty() || con_num.length() != 11) {
    JOptionPane.showMessageDialog(this, "Check Your Contact Number", "INCORRECT INPUT", JOptionPane.WARNING_MESSAGE);
    return;
}

     
    String nam = nam1.substring(0, 1).toUpperCase() + nam1.substring(1).toLowerCase();
    String last = last1.substring(0, 1).toUpperCase() + last1.substring(1).toLowerCase();
    String baranggaY = baranggaY1.substring(0, 1).toUpperCase() + baranggaY1.substring(1).toLowerCase();
    String citY =    citY1.substring(0, 1).toUpperCase() + citY1.substring(1).toLowerCase();
    String municipal = municipal1.substring(0, 1).toUpperCase() + municipal1.substring(1).toLowerCase();
    
    String formattedDate = null;
    if (agE != null) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM d, yyyy");
    formattedDate = dateFormat.format(agE); // Format the date to a string
}
    // Database connection and insertion code
    try {
        // Load the MySQL driver
        Class.forName("com.mysql.cj.jdbc.Driver");

        // Establish connection
        String url = "jdbc:mysql://localhost:3306/pet_license";
        Connection con = DriverManager.getConnection(url, "root", "");
        
         String checkQuery = "SELECT COUNT(*) FROM account_info WHERE account_name = ?";
        PreparedStatement checkPst = con.prepareStatement(checkQuery);
        checkPst.setString(1, user);
        ResultSet rs = checkPst.executeQuery();
        rs.next(); // Move to the first result row
        int count = rs.getInt(1); // Retrieve the count

        if (count > 0) {
            JOptionPane.showMessageDialog(this, "The account name already exists.", "Account Exists", JOptionPane.WARNING_MESSAGE);
            rs.close();
            checkPst.close();
            con.close();
            return; // Stop execution if the account already exists
        }

        
         // Check if the connection is successful
    if (con != null) {
        System.out.println("Connection successful.");
    } else {
        System.out.println("Connection failed.");
    }
    
        // Prepare the SQL query using PreparedStatement to avoid SQL injection
        String query = "INSERT INTO account_info(first_name, last_name, birth_date, contact_number, baranggay, city, province, account_name, password) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, nam);
        pst.setString(2, last);
        pst.setString(3, formattedDate);
        pst.setString(4, con_num);
        pst.setString(5, baranggaY);
        pst.setString(6, citY);
        pst.setString(7, municipal);
        pst.setString(8, user);
        pst.setString(9, pass);// Set the parameter (the name entered in the text field)

        // Execute the insert
        int rowsAffected = pst.executeUpdate();
        First_Interface pi = null;
        try {
            pi = new First_Interface();
        } catch (IOException ex) {
            Logger.getLogger(Sign_Up.class.getName()).log(Level.SEVERE, null, ex);
        }
        pi.setVisible(true);
        this.dispose();
        // Provide feedback
        if (rowsAffected > 0) {
            System.out.println("Record inserted successfully.");
        } else {
            System.out.println("Failed to insert the record.");
        }

        // Close the connection
        pst.close();
        con.close();

    } catch (ClassNotFoundException e) {
        System.out.println("MySQL JDBC Driver not found!");
        e.printStackTrace();
    } catch (SQLException e) {
        System.out.println("SQLException: " + e.getMessage());
        e.printStackTrace();
    }
        
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            First_Interface pi = new First_Interface();
            pi.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(Sign_Up.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Sign_Up().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Sign_Up.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account;
    private javax.swing.JTextField baranggay;
    private javax.swing.JTextField city;
    private javax.swing.JTextField contactNum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField municipality;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    // End of variables declaration//GEN-END:variables
}
